project:
  type: website
  output-dir: _site

website:
  title: "Where Does Sarcasm Live?"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    css: custom.css

jupyter: python3
